### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by nujcharee** [avinmathew/power-bi-leaflet-custom-visual#1]
Hi there,
Cloned your repo and changed it to api 1.10.0, can see the map when loaded custom visual into powerbi but cant seem to plot any data, can you advice? Many thanks :)

**Comment by avinmathew** [comment]
@nujcharee how are you plotting data?

**Comment by nujcharee** [comment]
hey there @avinmathew I use postcode and one measure.

**Comment by avinmathew** [comment]
@nujcharee This isn't meant to be a visual you use out of the box, but instead a foundation on which you add [Leaflet](https://leafletjs.com/) JavaScript code on top of this to render whatever you want.
